spring.application.name=CajerosService

server.port=8080

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=UBANCOSEP2025
spring.datasource.password=password1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

security.jwt.secret=lapalabraclave_pruebatecnica_jwt_ulis_ideal64chaN
security.jwt.expiration-minutes=60
security.jwt.issuer=banco-api

logging.level.org.springframework.security=DEBUG

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.jdbc.fetch_size=10
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
